import type { Metadata } from "next";
import {EB_Garamond, Montserrat } from "next/font/google"; 
import "@/styles/globals.css";


import WhatsappButton from "@/components/WhatsappButton";
import Header from "@/sections/Header";
import { Footer } from "@/sections";

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
});


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className=" relative scroll-smooth">
      <body className={`${montserrat.variable} ${ebGaramond.variable}  antialiased`}>
        <Header />
        {children}
        <WhatsappButton />
        <Footer />
      </body>
    </html>
  );
}
