import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "@/styles/globals.css";
import WhatsappButton from "@/components/WhatsappButton";
import Header from "@/sections/Header";
import { Footer } from "@/sections";

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Include multiple weights if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="scroll-smooth">
      <body className={`${merriweather.variable}  antialiased`}>
        <Header />
        {children}
        <WhatsappButton />
        <Footer />
      </body>
    </html>
  );
}
